import { Inter } from "next/font/google";
import "./globals.css";
import { RoomProvider } from "@/context/RoomContext";
import { DrawProvider } from "@/context/DrawContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RoomProvider>
          <DrawProvider>
            {children}
          </DrawProvider>
        </RoomProvider>
      </body>
    </html>
  );
}
